WIP Trying to fix installation of Python bindings.
With the current changes, the compilation process always succeeds (both in regular and editable mode) but there are still two problems:

    - In editable mode seems that the final copy of the built .so to the destination folder fails
    ("copying build/temp.linux-x86_64-3.6/src/dawn4py/_dawn4py.cpython-36m-x86_64-linux-gnu.so -> build/lib.linux-x86_64-3.6/dawn4py
    error: could not create 'build/lib.linux-x86_64-3.6/dawn4py/_dawn4py.cpython-36m-x86_64-linux-gnu.so': No such file or directory"
)

    - In regular mode, the package is fully built and installed, but the protocol buffer python files are missing and thus dawn4py trying import fails

I think the Python side of the installation is more or less fixed, and the remaining issues should be fixed in the CMake side.